CREATE TABLE profile_catalog (
  type TEXT NOT NULL,
  group_key TEXT NOT NULL,
  catalog_key TEXT NOT NULL,
  title TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0, 1)),
  position INTEGER NOT NULL,
  PRIMARY KEY(type, group_key, catalog_key)
);

INSERT INTO profile_catalog(type, group_key, catalog_key, title, active, position) VALUES
  ('professor', 'matriculados', 'iranildo', 'Iranildo', 1, 10),
  ('professor', 'matriculados', 'elohim', 'Elohim', 1, 20),
  ('professor', 'matriculados', 'xico', 'Xico', 1, 30),
  ('professor', 'matriculados', 'aquiles', 'Aquiles', 1, 40),
  ('professor', 'matriculados', 'ruan', 'Ruan', 1, 50),
  ('professor', 'matriculados', 'cadu', 'Cadu', 1, 60),
  ('professor', 'cancelados', 'iranildo', 'Iranildo', 1, 10),
  ('professor', 'cancelados', 'elohim', 'Elohim', 1, 20),
  ('professor', 'cancelados', 'xico', 'Xico', 1, 30),
  ('professor', 'cancelados', 'ruan', 'Ruan', 1, 40),
  ('professor', 'cancelados', 'cadu', 'Cadu', 1, 50),
  ('professor', 'cancelados', 'wallyson', 'Wallyson', 1, 60),
  ('professor', 'cancelados', 'lucas', 'Lucas', 1, 70),
  ('professor', 'cancelados', 'genuca', 'Genuca', 1, 80),
  ('etiqueta', 'publico', 'idoso', 'Idoso', 1, 10),
  ('etiqueta', 'publico', 'saude', 'Saúde', 1, 20),
  ('etiqueta', 'publico', 'estetica', 'Estética', 1, 30),
  ('etiqueta', 'publico', 'dores', 'Dores', 1, 40),
  ('etiqueta', 'publico', 'corrida', 'Corrida', 1, 50),
  ('etiqueta', 'publico', 'performance', 'Performance', 1, 60),
  ('etiqueta', 'comercial', 'risco_de_churn', 'Risco de Churn', 1, 10),
  ('etiqueta', 'comercial', 'sem_fidelizacao', 'Sem fidelização', 1, 20),
  ('etiqueta', 'comercial', 'elohim', 'Elohim', 1, 30),
  ('etiqueta', 'comercial', 'coach', 'Coach', 1, 40),
  ('perfil_pagamento', 'global', 'sem_historico', 'Sem histórico', 1, 10),
  ('perfil_pagamento', 'global', 'bom_pagador', 'Bom pagador', 1, 20),
  ('perfil_pagamento', 'global', 'eventual_fora_prazo', 'Pagamento eventual fora do prazo', 1, 30),
  ('perfil_pagamento', 'global', 'frequente_fora_prazo', 'Pagamento frequentemente fora do prazo', 1, 40),
  ('perfil_pagamento', 'global', 'cobranca_recorrente', 'Cobrança recorrente necessária', 1, 50),
  ('perfil_pagamento', 'global', 'em_acompanhamento', 'Em acompanhamento', 1, 60);
